apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: tododb
  name: tododb
  selfLink: /apis/apps.openshift.io/v1/namespaces/zhuangpeng0514-review-multicontainer/deploymentconfigs/tododb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: tododb
    deploymentconfig: tododb
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: tododb
        deploymentconfig: tododb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: todo
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: tododb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: tododb
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
        imagePullPolicy: Always
        name: tododb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: tododb-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tododb-volume-1
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - tododb
      from:
        kind: ImageStreamTag
        name: tododb:latest
        namespace: zhuangpeng0514-review-multicontainer
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
